import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart' as sb;

import '../models/notification_item.dart';
import '../models/notification_preferences.dart';
import 'auth_service.dart';

/// Real Supabase-backed notifications repository (Phase 6, spec §9/§10).
///
/// This covers the full in-app notification system — real rows generated by
/// friend requests/accepts and channel joins, real global + per-channel
/// preferences. Actually delivering a push to a device via Firebase Cloud
/// Messaging needs a Firebase project and a server-side sender (a Supabase
/// Edge Function calling the FCM API); [registerDeviceToken] stores the
/// token so that's ready to wire in once that project exists.
class NotificationsRepository {
  sb.SupabaseClient get _client => sb.Supabase.instance.client;
  String? get _uid => _client.auth.currentUser?.id;

  Future<List<NotificationItem>> fetchNotifications() async {
    final uid = _uid;
    if (uid == null) return [];
    final rows = await _client
        .from('notifications')
        .select()
        .eq('user_id', uid)
        .order('created_at', ascending: false)
        .limit(50);
    return (rows as List).map((r) => _fromRow(r as Map<String, dynamic>)).toList();
  }

  Future<void> markRead(String notificationId) =>
      _client.rpc('mark_notification_read', params: {'p_notification_id': notificationId});

  Future<NotificationPreferences> fetchPreferences() async {
    final uid = _uid;
    if (uid == null) return const NotificationPreferences();
    final row =
        await _client.from('notification_preferences').select().eq('user_id', uid).maybeSingle();
    if (row == null) return const NotificationPreferences();
    return NotificationPreferences(
      friendRequests: row['friend_requests'] as bool? ?? true,
      channelInvitations: row['channel_invitations'] as bool? ?? true,
      mentions: row['mentions'] as bool? ?? true,
      announcements: row['announcements'] as bool? ?? true,
      voiceActivity: row['voice_activity'] as bool? ?? false,
      directMessages: row['direct_messages'] as bool? ?? true,
    );
  }

  Future<void> updatePreferences(NotificationPreferences prefs) async {
    final uid = _uid;
    if (uid == null) return;
    await _client.from('notification_preferences').upsert({
      'user_id': uid,
      'friend_requests': prefs.friendRequests,
      'channel_invitations': prefs.channelInvitations,
      'mentions': prefs.mentions,
      'announcements': prefs.announcements,
      'voice_activity': prefs.voiceActivity,
      'direct_messages': prefs.directMessages,
      'updated_at': DateTime.now().toIso8601String(),
    });
  }

  Future<void> setChannelNotificationLevel(String channelId, ChannelNotificationLevel level) =>
      _client.rpc('set_channel_notification_level', params: {
        'p_channel_id': channelId,
        'p_level': level.dbValue,
      });

  /// Stores this device's FCM/APNs token so a future server-side sender can
  /// target it. No-op until push registration is actually wired (Firebase
  /// project pending).
  Future<void> registerDeviceToken(String token, String platform) =>
      _client.rpc('register_device_token', params: {'p_token': token, 'p_platform': platform});

  NotificationItem _fromRow(Map<String, dynamic> row) => NotificationItem(
        id: row['id'] as String,
        type: NotificationTypeX.fromDb(row['type'] as String),
        title: row['title'] as String,
        body: row['body'] as String,
        channelId: row['channel_id'] as String?,
        senderId: row['sender_id'] as String?,
        read: row['read'] as bool? ?? false,
        createdAt: DateTime.parse(row['created_at'] as String),
      );
}

final notificationsRepositoryProvider = Provider<NotificationsRepository>(
  (ref) => NotificationsRepository(),
);

final notificationsProvider = FutureProvider<List<NotificationItem>>((ref) {
  ref.watch(authServiceProvider);
  return ref.watch(notificationsRepositoryProvider).fetchNotifications();
});

final unreadNotificationCountProvider = FutureProvider<int>((ref) async {
  final items = await ref.watch(notificationsProvider.future);
  return items.where((n) => !n.read).length;
});

final notificationPreferencesProvider = FutureProvider<NotificationPreferences>((ref) {
  ref.watch(authServiceProvider);
  return ref.watch(notificationsRepositoryProvider).fetchPreferences();
});

/// Refreshes notification-related providers — call after marking read or
/// changing preferences.
void refreshNotificationsProviders(WidgetRef ref) {
  ref.invalidate(notificationsProvider);
  ref.invalidate(notificationPreferencesProvider);
}
