/// A notification type (spec §9). `mentions`/`direct_messages` aren't
/// generated by anything yet (no text chat/mentions feature exists) but the
/// schema/preferences already have room for them.
enum NotificationType { friendRequest, friendAccept, channelActivity }

extension NotificationTypeX on NotificationType {
  static NotificationType fromDb(String s) => switch (s) {
        'friend_request' => NotificationType.friendRequest,
        'friend_accept' => NotificationType.friendAccept,
        _ => NotificationType.channelActivity,
      };
}

/// A row in the `notifications` table (spec §12).
class NotificationItem {
  final String id;
  final NotificationType type;
  final String title;
  final String body;
  final String? channelId;
  final String? senderId;
  final bool read;
  final DateTime createdAt;

  const NotificationItem({
    required this.id,
    required this.type,
    required this.title,
    required this.body,
    this.channelId,
    this.senderId,
    required this.read,
    required this.createdAt,
  });
}
